// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package mock
//

// Package mock is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/TheLuckymadman/metawatch/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddMetric mocks base method.
func (m *MockService) AddMetric(ctx context.Context, metricName, metricValue, metricType, agentIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMetric", ctx, metricName, metricValue, metricType, agentIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMetric indicates an expected call of AddMetric.
func (mr *MockServiceMockRecorder) AddMetric(ctx, metricName, metricValue, metricType, agentIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMetric", reflect.TypeOf((*MockService)(nil).AddMetric), ctx, metricName, metricValue, metricType, agentIP)
}

// AddObjMetric mocks base method.
func (m *MockService) AddObjMetric(ctx context.Context, metric model.Metrics, agentIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddObjMetric", ctx, metric, agentIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddObjMetric indicates an expected call of AddObjMetric.
func (mr *MockServiceMockRecorder) AddObjMetric(ctx, metric, agentIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddObjMetric", reflect.TypeOf((*MockService)(nil).AddObjMetric), ctx, metric, agentIP)
}

// AddObjMetrics mocks base method.
func (m *MockService) AddObjMetrics(ctx context.Context, metrics []model.Metrics, agentIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddObjMetrics", ctx, metrics, agentIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddObjMetrics indicates an expected call of AddObjMetrics.
func (mr *MockServiceMockRecorder) AddObjMetrics(ctx, metrics, agentIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddObjMetrics", reflect.TypeOf((*MockService)(nil).AddObjMetrics), ctx, metrics, agentIP)
}

// GetObjMetric mocks base method.
func (m *MockService) GetObjMetric(ctx context.Context, metricReq model.Metrics, agentIP string) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjMetric", ctx, metricReq, agentIP)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjMetric indicates an expected call of GetObjMetric.
func (mr *MockServiceMockRecorder) GetObjMetric(ctx, metricReq, agentIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjMetric", reflect.TypeOf((*MockService)(nil).GetObjMetric), ctx, metricReq, agentIP)
}

// ListMetric mocks base method.
func (m *MockService) ListMetric(ctx context.Context) (map[string]*model.Metrics, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetric", ctx)
	ret0, _ := ret[0].(map[string]*model.Metrics)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMetric indicates an expected call of ListMetric.
func (mr *MockServiceMockRecorder) ListMetric(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetric", reflect.TypeOf((*MockService)(nil).ListMetric), ctx)
}

// PingDB mocks base method.
func (m *MockService) PingDB(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingDB", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingDB indicates an expected call of PingDB.
func (mr *MockServiceMockRecorder) PingDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingDB", reflect.TypeOf((*MockService)(nil).PingDB), ctx)
}
