
// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go

package main

func (rs *st) Reset() {
	if rs == nil {
		return
	}  
	rs.i = 0  
	rs.b = false  
	if rs.ptrI != nil { 
		*rs.ptrI = 0
	}
	  
	rs.st2.Reset()  
	if rs.ptrSt2 != nil {
		rs.ptrSt2.Reset()
	}  
	rs.sl1 = rs.sl1[:0]  
	clear(rs.mp1)  
	rs.s = ""  
	rs.ptrS = ""  
	rs.ptrB = false  
	if rs.ptrSl1 != nil {
		*rs.ptrSl1 = (*rs.ptrSl1)[:0]
	}  
	if rs.ptrMp1 != nil {
		clear(*rs.ptrMp1)
	}
}

func (rs *st2) Reset() {
	if rs == nil {
		return
	}  
	rs.i2 = 0  
	rs.st2 = ""
}

