
// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go

package model

func (rs *Metrics) Reset() {
	if rs == nil {
		return
	}  
	rs.ID = ""  
	rs.MType = ""  
	if rs.Delta != nil { 
		*rs.Delta = 0
	}
	  
	if rs.Value != nil { 
		*rs.Value = 0
	}
	  
	rs.Hash = ""
}

