package main

import (
	"fmt"
	"go/ast"
	"go/types"
	"log/slog"
	"os"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go

package {{ .PackageName }}
{{ range $sName, $snippets := .StructsWithResetFieldSnpts }}
func (rs *{{ $sName }}) Reset() {
	if rs == nil {
		return
	}
	
	{{- range $snippets }}  
	{{.}}
	{{- end }}
}
{{ end }}
`

var tmpl = template.Must(template.New("reset").Parse(templateStr))

var StructsWithResetMethod = make(map[*types.Named]struct{})

type TemplateValues struct {
	PackageName                string
	StructsWithResetFieldSnpts map[string][]string
}

type StructInfo struct {
	Name       string
	TypeInfo   types.Type
	FieldsInfo map[string]types.Type
}

type PackageInfo struct {
	Name        string
	StructsInfo []StructInfo
}

func isGoDir(entries []os.DirEntry) bool {
	var isGoDir bool
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") {
			isGoDir = true
			break
		}
	}
	return isGoDir
}

func getGoDirs(path string) ([]string, error) {
	var goDirPaths []string
	items, err := os.ReadDir(path)
	if err != nil {
		return nil, err
	}
	if isGoDir(items) {
		goDirPaths = append(goDirPaths, path)
	}
	for _, item := range items {
		if item.Type().IsDir() {
			dirs, err := getGoDirs(path + "/" + item.Name())
			if err != nil {
				return nil, err
			}
			goDirPaths = append(goDirPaths, dirs...)
		}
	}
	return goDirPaths, nil
}

func getDirPackag(pattern string) (*packages.Package, error) {
	cfg := &packages.Config{
		Mode: packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedName,
	}

	pkgs, err := packages.Load(cfg, pattern)
	if err != nil {
		return nil, err
	}
	if len(pkgs) == 0 {
		return nil, fmt.Errorf("no packages found")
	}
	return pkgs[0], nil
}

func getPkgStructsByComment(pkg *packages.Package, comment string) (PackageInfo, error) {
	structsInfo := []StructInfo{}
	for _, file := range pkg.Syntax {
		for _, d := range file.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Doc == nil || !strings.Contains(gd.Doc.Text(), comment) {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				obj := pkg.TypesInfo.Defs[ts.Name]
				namedType, ok := obj.Type().(*types.Named)
				if !ok {
					continue
				}
				StructsWithResetMethod[namedType] = struct{}{}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				fields := make(map[string]types.Type)

				for _, field := range st.Fields.List {
					for _, name := range field.Names {
						tv := pkg.TypesInfo.Types[field.Type]
						fields[name.Name] = tv.Type
					}
				}
				structsInfo = append(structsInfo, StructInfo{
					Name:       ts.Name.Name,
					TypeInfo:   namedType,
					FieldsInfo: fields,
				})
			}
		}

	}
	return PackageInfo{
		Name:        pkg.Name,
		StructsInfo: structsInfo,
	}, nil
}

func getType(fType types.Type) any {
	if basicType, ok := fType.Underlying().(*types.Basic); ok {
		return basicType
	}
	if sliceType, ok := fType.Underlying().(*types.Slice); ok {
		return sliceType
	}
	if mapType, ok := fType.Underlying().(*types.Map); ok {
		return mapType
	}
	if structType, ok := fType.Underlying().(*types.Struct); ok {
		return structType
	}
	if ptrType, ok := fType.Underlying().(*types.Pointer); ok {
		return getType(ptrType.Elem())
	}
	return types.Invalid
}

func generateResetValue(fName string, fType types.Type) (string, error) {
	slog.Debug("generateResetValue", fName, fType)
	t := getType(fType)
	if basicType, ok := fType.(*types.Basic); ok {
		switch basicType.Kind() {
		case types.Int:
			{
				return fmt.Sprintf("rs.%s = 0", fName), nil
			}
		case types.Int32:
			{
				return fmt.Sprintf("rs.%s = 0", fName), nil
			}
		case types.Int64:
			{
				return fmt.Sprintf("rs.%s = 0", fName), nil
			}
		case types.Float32:
			{
				return fmt.Sprintf("rs.%s = 0", fName), nil
			}
		case types.Float64:
			{
				return fmt.Sprintf("rs.%s = 0", fName), nil
			}
		case types.String:
			{
				return fmt.Sprintf("rs.%s = \"\"", fName), nil
			}
		case types.Bool:
			{
				return fmt.Sprintf("rs.%s = false", fName), nil
			}
		case types.Invalid:
			{
				return "", fmt.Errorf("no basic type %s for field name %s", fType.String(), fName)
			}
		}
	}
	if ptrType, ok := fType.(*types.Pointer); ok {
		if basicType, ok := t.(*types.Basic); ok {
			switch basicType.Kind() {
			case types.Int:
				{
					return fmt.Sprintf(`if rs.%s != nil { 
		*rs.%s = 0
	}
	`, fName, fName), nil
				}
			case types.Uint32:
				{
					return fmt.Sprintf(`if rs.%s != nil { 
		*rs.%s = 0
	}
	`, fName, fName), nil
				}
			case types.Int64:
				{
					return fmt.Sprintf(`if rs.%s != nil { 
		*rs.%s = 0
	}
	`, fName, fName), nil
				}
			case types.Float32:
				{
					return fmt.Sprintf(`if rs.%s != nil { 
		*rs.%s = 0
	}
	`, fName, fName), nil
				}
			case types.Float64:
				{
					return fmt.Sprintf(`if rs.%s != nil { 
		*rs.%s = 0
	}
	`, fName, fName), nil
				}
			case types.String:
				{
					return fmt.Sprintf(`if rs.%s != nil { 
		*rs.%s = ""
	}
	`, fName, fName), nil
				}
			case types.Invalid:
				{
					return "", fmt.Errorf("no basic type %s for field name %s", fType.String(), fName)
				}
			}
		}

		if _, ok := t.(*types.Slice); ok {
			return fmt.Sprintf(`if rs.%s != nil {
		*rs.%s = (*rs.%s)[:0]
	}`, fName, fName, fName), nil
		}

		if _, ok := t.(*types.Map); ok {
			return fmt.Sprintf(`if rs.%s != nil {
		clear(*rs.%s)
	}`, fName, fName), nil
		}

		if namedType, ok := ptrType.Elem().(*types.Named); ok {
			if _, ok := StructsWithResetMethod[namedType]; ok {
				return fmt.Sprintf(`if rs.%s != nil {
		rs.%s.Reset()
	}`, fName, fName), nil
			} else {
				return "", nil
			}
		}
	}
	if _, ok := t.(*types.Slice); ok {
		return fmt.Sprintf("rs.%s = rs.%s[:0]", fName, fName), nil
	}

	if _, ok := t.(*types.Map); ok {
		return fmt.Sprintf("clear(rs.%s)", fName), nil
	}

	if namedType, ok := fType.(*types.Named); ok {
		if _, ok := StructsWithResetMethod[namedType]; ok {
			slog.Debug("generateResetValue", "nameType", namedType)
			return fmt.Sprintf("rs.%s.Reset()", fName), nil
		} else {
			return "", nil
		}
	}
	return "", fmt.Errorf("no reset code for variable name %s with type %s", fName, fType.String())
}

func main() {
	var path = "../.."
	if len(os.Args) == 2 {
		path = os.Args[1]
	}
	slog.SetLogLoggerLevel(slog.LevelDebug)
	goDirsPath, err := getGoDirs(path)
	if err != nil {
		slog.Error("main", "err", err.Error())
		return
	}
	slog.Debug("main", "GO dirs", goDirsPath)

	for _, dir := range goDirsPath {
		pkg, err := getDirPackag(dir)
		if err != nil {
			slog.Error("main", "error", err)
		}

		packageInfo, err := getPkgStructsByComment(pkg, "generate:reset")
		if err != nil {
			slog.Error("main", "error", err)
			return
		}

		if len(packageInfo.StructsInfo) == 0 {
			continue
		}
		slog.Info("main", "package to processed: ", packageInfo)
		structsWithResetFieldSnpts := make(map[string][]string)

		for _, st := range packageInfo.StructsInfo {
			var resetFieldSnippets []string
			for fName, fType := range st.FieldsInfo {
				resetFieldSnippet, rerr := generateResetValue(fName, fType)
				if rerr != nil {
					slog.Error("main", "error", rerr)
					return
				}
				if resetFieldSnippet != "" {
					resetFieldSnippets = append(resetFieldSnippets, resetFieldSnippet)
				}
			}
			structsWithResetFieldSnpts[st.Name] = resetFieldSnippets
		}
		templateValues := TemplateValues{
			packageInfo.Name,
			structsWithResetFieldSnpts,
		}
		file, _ := os.Create(dir + "/reset.gen.go")
		err = tmpl.Execute(file, templateValues)
		if err != nil {
			fmt.Println("Error: ", err)
			return
		}
	}
}
