// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen --source=interfaces.go --destination=mocks/mock_storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/TheLuckymadman/metawatch/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddMetric mocks base method.
func (m *MockStorage) AddMetric(ctx context.Context, agentID, metricType, metricName string, value float64, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMetric", ctx, agentID, metricType, metricName, value, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMetric indicates an expected call of AddMetric.
func (mr *MockStorageMockRecorder) AddMetric(ctx, agentID, metricType, metricName, value, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMetric", reflect.TypeOf((*MockStorage)(nil).AddMetric), ctx, agentID, metricType, metricName, value, delta)
}

// AddMetrics mocks base method.
func (m *MockStorage) AddMetrics(ctx context.Context, agentID string, metrics []model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMetrics", ctx, agentID, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMetrics indicates an expected call of AddMetrics.
func (mr *MockStorageMockRecorder) AddMetrics(ctx, agentID, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMetrics", reflect.TypeOf((*MockStorage)(nil).AddMetrics), ctx, agentID, metrics)
}

// Close mocks base method.
func (m *MockStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// GetMetric mocks base method.
func (m *MockStorage) GetMetric(ctx context.Context, agentID, metricType, metricName string) (float64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", ctx, agentID, metricType, metricName)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockStorageMockRecorder) GetMetric(ctx, agentID, metricType, metricName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockStorage)(nil).GetMetric), ctx, agentID, metricType, metricName)
}

// GetObjMetric mocks base method.
func (m *MockStorage) GetObjMetric(ctx context.Context, agentID, metricType, metricName string) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjMetric", ctx, agentID, metricType, metricName)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjMetric indicates an expected call of GetObjMetric.
func (mr *MockStorageMockRecorder) GetObjMetric(ctx, agentID, metricType, metricName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjMetric", reflect.TypeOf((*MockStorage)(nil).GetObjMetric), ctx, agentID, metricType, metricName)
}

// GetStore mocks base method.
func (m *MockStorage) GetStore(ctx context.Context) (map[string]*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", ctx)
	ret0, _ := ret[0].(map[string]*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockStorageMockRecorder) GetStore(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockStorage)(nil).GetStore), ctx)
}

// PingDB mocks base method.
func (m *MockStorage) PingDB(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingDB", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingDB indicates an expected call of PingDB.
func (mr *MockStorageMockRecorder) PingDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingDB", reflect.TypeOf((*MockStorage)(nil).PingDB), ctx)
}

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockObserver) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockObserverMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockObserver)(nil).GetID))
}

// Update mocks base method.
func (m *MockObserver) Update(ctx context.Context, metrics []model.Metrics, agentIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, metrics, agentIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockObserverMockRecorder) Update(ctx, metrics, agentIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockObserver)(nil).Update), ctx, metrics, agentIP)
}

// MockAudit is a mock of Audit interface.
type MockAudit struct {
	ctrl     *gomock.Controller
	recorder *MockAuditMockRecorder
	isgomock struct{}
}

// MockAuditMockRecorder is the mock recorder for MockAudit.
type MockAuditMockRecorder struct {
	mock *MockAudit
}

// NewMockAudit creates a new mock instance.
func NewMockAudit(ctrl *gomock.Controller) *MockAudit {
	mock := &MockAudit{ctrl: ctrl}
	mock.recorder = &MockAuditMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudit) EXPECT() *MockAuditMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockAudit) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockAuditMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockAudit)(nil).GetID))
}

// Update mocks base method.
func (m *MockAudit) Update(ctx context.Context, metrics []model.Metrics, agentIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, metrics, agentIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAuditMockRecorder) Update(ctx, metrics, agentIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAudit)(nil).Update), ctx, metrics, agentIP)
}
